(function(){
  const el = q=>document.querySelector(q), els=q=>Array.from(document.querySelectorAll(q));
  const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
  const DEFAULTS={statuses:[{name:"OK",color:"#10b981"},{name:"Needs",color:"#f59e0b"},{name:"OOS",color:"#ef4444"}],checklist:["Caps present/intact","No leaks","Threads clean"],tasks:["Lubricate stem","Paint touch-up","Replace gaskets"]};
  const state={data:store.get("rc_data",{hydrants:[],details:[],locks:{masters:[],details:[]}}),ui:{activeTab:"tab-dashboard"}};
  const meta={statuses:store.get("rc_statuses",DEFAULTS.statuses),checklist:store.get("rc_checklist",DEFAULTS.checklist),tasks:store.get("rc_tasks",DEFAULTS.tasks)};
  if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));}
  function activateTab(id){state.ui.activeTab=id;els(".tab").forEach(s=>s.classList.remove("active"));el("#"+id).classList.add("active");els(".tab-btn").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));el("#lowerBar").style.display=(id==="tab-flow")?"flex":"none";if(id==="tab-dashboard")renderDashboard();if(id==="tab-hydrants")renderHydrants();if(id==="tab-settings"){renderSettingsEditors();fillStatusSelect();}if(id==="tab-mi"){fillStatusSelect();renderMiLists();}}
  els(".tab-btn").forEach(b=>b.addEventListener("click",()=>activateTab(b.dataset.tab)));activateTab(state.ui.activeTab);
  function toast(m,t="ok"){const d=document.createElement("div");d.className="toast "+t;d.textContent=m;el("#toastContainer").appendChild(d);setTimeout(()=>d.remove(),3500);}
  function parseCSV(text){const rows=[];let i=0,field="",row=[],inQ=false;while(i<text.length){const c=text[i];if(inQ){if(c=='"'){if(text[i+1]=='"'){field+='"';i++;}else inQ=false;}else field+=c;}else{if(c=='"')inQ=true;else if(c==','){row.push(field);field="";}else if(c=='\n'||c=='\r'){if(field or row){row.append(field);rows.append(row);field="";row=[]}if(c=='\r' and text[i+1]=='\n')i+=1}else field+=c}i+=1}if(field or row){row.append(field);rows.append(row)}return rows;}
  function parseCSV(text){const rows=[];let i=0,field="",row=[],inQ=false;while(i<text.length){const c=text[i];if(inQ){if(c=='"'){if(text[i+1]=='"'){field+='"';i++;}else inQ=false;}else field+=c;}else{if(c=='"')inQ=true;else if(c==','){row.push(field);field="";}else if(c=='\n'||c=='\r'){if(field.length||row.length){row.push(field);rows.push(row);field="";row=[]}if(c=='\r'&&text[i+1]=='\n')i++}else field+=c}i++}if(field.length||row.length){row.push(field);rows.push(row)}return rows;}
  function renderDashboard(){const hyds=state.data.hydrants,dist={},stat={};hyds.forEach(h=>{const d=h.District||"Unspecified";dist[d]=(dist[d]||0)+1;const s=h.Status||"OK";stat[s]=(stat[s]||0)+1});const dEl=el("#districtTotals");dEl.innerHTML="";Object.entries(dist).forEach(([d,c])=>{const div=document.createElement("div");div.className="status-chip";div.innerHTML=`<strong>${d}</strong><span>${c}</span>`;dEl.appendChild(div)});const sEl=el("#statusTotals");sEl.innerHTML="";Object.entries(stat).forEach(([s,c])=>{const ss=meta.statuses.find(x=>x.name===s);const color=ss?ss.color:"#444";const div=document.createElement("div");div.className="status-chip";div.innerHTML=`<span class="status-swatch" style="background:${color}"></span><span>${s}</span><strong>${c}</strong>`;sEl.appendChild(div)})}
  el("#dashRefresh").addEventListener("click",renderDashboard);
  function renderHydrants(){const tbody=el("#h_rows");const q=(el("#h_search").value||"").toLowerCase();const rows=state.data.hydrants.filter(h=>[h.HydID,h.District,h.Location,h.Status].join(" ").toLowerCase().includes(q)).map(h=>{const div=document.createElement("div");div.className="row";div.innerHTML=`<div>${h.HydID||""}</div><div>${h.District||""}</div><div>${h.Location||""}</div><div>${h.Status||""}</div>`;div.addEventListener("click",()=>{el("#f_hydrant").value=h.HydID||"";el("#f_location").value=h.Location||"";el("#m_hydrant").value=h.HydID||"";el("#m_location").value=h.Location||"";activateTab("tab-flow")});return div});tbody.innerHTML="";rows.forEach(r=>tbody.appendChild(r))}
  el("#h_search").addEventListener("input",renderHydrants);el("#h_clear").addEventListener("click",()=>{el("#h_search").value="";renderHydrants()});
  function renderSettingsEditors(){const wrap=el("#statusEditor");wrap.innerHTML="";meta.statuses.forEach((s,i)=>{const row=document.createElement("div");row.className="toolbar";row.style.gap="12px";row.innerHTML=`<input value="${s.name}" data-i="${i}" class="s_name"><input type="color" value="${s.color}" data-i="${i}" class="s_col"><button class="btn ghost del" data-i="${i}">Delete</button>`;wrap.appendChild(row)});wrap.querySelectorAll(".s_name").forEach(inp=>inp.addEventListener("input",e=>{meta.statuses[+e.target.dataset.i].name=e.target.value.trim();store.set("rc_statuses",meta.statuses);renderDashboard()}));wrap.querySelectorAll(".s_col").forEach(inp=>inp.addEventListener("input",e=>{meta.statuses[+e.target.dataset.i].color=e.target.value;store.set("rc_statuses",meta.statuses);renderDashboard()}));wrap.querySelectorAll(".del").forEach(btn=>btn.addEventListener("click",e=>{meta.statuses.splice(+e.target.dataset.i,1);store.set("rc_statuses",meta.statuses);renderSettingsEditors();renderDashboard()}));const cwrap=el("#checklistEditor");cwrap.innerHTML="";meta.checklist.forEach((t,i)=>{const row=document.createElement("div");row.className="toolbar";row.innerHTML=`<input value="${t}" data-i="${i}" class="c_item"><button class="btn ghost c_del" data-i="${i}">Delete</button>`;cwrap.appendChild(row)});cwrap.querySelectorAll(".c_item").forEach(inp=>inp.addEventListener("input",e=>{meta.checklist[+e.target.dataset.i]=e.target.value;store.set("rc_checklist",meta.checklist)}));cwrap.querySelectorAll(".c_del").forEach(btn=>btn.addEventListener("click",e=>{meta.checklist.splice(+e.target.dataset.i,1);store.set("rc_checklist",meta.checklist);renderSettingsEditors()}));const twrap=el("#tasksEditor");twrap.innerHTML="";meta.tasks.forEach((t,i)=>{const row=document.createElement("div");row.className="toolbar";row.innerHTML=`<input value="${t}" data-i="${i}" class="t_item"><button class="btn ghost t_del" data-i="${i}">Delete</button>`;twrap.appendChild(row)});twrap.querySelectorAll(".t_item").forEach(inp=>inp.addEventListener("input",e=>{meta.tasks[+e.target.dataset.i]=e.target.value;store.set("rc_tasks",meta.tasks)}));twrap.querySelectorAll(".t_del").forEach(btn=>btn.addEventListener("click",e=>{meta.tasks.splice(+e.target.dataset.i,1);store.set("rc_tasks",meta.tasks);renderSettingsEditors()}))}
  el("#addStatus").addEventListener("click",()=>{meta.statuses.push({name:"New",color:"#888888"});store.set("rc_statuses",meta.statuses);renderSettingsEditors()});
  el("#addCheck").addEventListener("click",()=>{meta.checklist.push("New item");store.set("rc_checklist",meta.checklist);renderSettingsEditors()});
  el("#addTask").addEventListener("click",()=>{meta.tasks.push("New task");store.set("rc_tasks",meta.tasks);renderSettingsEditors()});
  function fillStatusSelect(){const sel=el("#m_status");sel.innerHTML="";meta.statuses.forEach(s=>{const o=document.createElement("option");o.value=s.name;o.textContent=s.name;sel.appendChild(o)})}
  function renderMiLists(){const c=el("#m_checklist"),t=el("#m_tasks");c.innerHTML="";t.innerHTML="";meta.checklist.forEach((txt,i)=>{const row=document.createElement("label");row.className="toolbar";row.innerHTML=`<input type="checkbox"><span>${txt}</span>`;c.appendChild(row)});meta.tasks.forEach((txt,i)=>{const row=document.createElement("label");row.className="toolbar";row.innerHTML=`<input type="checkbox"><span>${txt}</span>`;t.appendChild(row)})}
  function ensureRequiredFilled(p){const loc=el(`#${p}_location`).value.trim(),ins=el(`#${p}_inspector`).value.trim(),hyd=el(`#${p}_hydrant`).value.trim(),date=el(`#${p}_date`).value.trim();const ok=!!(loc&&ins&&hyd&&date);if(p==="f"){el("#flowSection2").toggleAttribute("disabled",!ok);el("#flowSection3").toggleAttribute("disabled",!ok)}return ok}
  ["f_location","f_inspector","f_hydrant","f_date"].forEach(id=>el("#"+id).addEventListener("input",()=>ensureRequiredFilled("f")));
  ["m_location","m_inspector","m_hydrant","m_date"].forEach(id=>el("#"+id).addEventListener("input",()=>ensureRequiredFilled("m")));
  function calcFlow(){const pitot=parseFloat(el("#f_pitot").value||"0")||0;let totalQ=0;els(".outlet-row").forEach(r=>{const d=parseFloat(r.querySelector(".o_d").value||"0")||0;const c=parseFloat(r.querySelector(".o_c").value||"0.9")||0.9;const n=parseInt(r.querySelector(".o_n").value||"1")||1;const qOne=29.83*c*(d*d)*Math.sqrt(Math.max(pitot,0));totalQ+=qOne*n});const s=parseFloat(el("#f_static").value||"0")||0;const r=parseFloat(el("#f_residual").value||"0")||0;let aff=0;if(s>r&&s>20&&r>=0){const factor=Math.pow((s-20)/(s-r),0.54);aff=totalQ*factor}el("#r_total").textContent=totalQ?Math.round(totalQ):"—";el("#r_aff").textContent=aff?Math.round(aff):"—";return{totalQ,aff}}
  el("#calc").addEventListener("click",()=>{if(!ensureRequiredFilled("f")){toast("Fill the required top section first.","warn");return}calcFlow()});
  el("#addOutlet").addEventListener("click",()=>{const row=document.createElement("div");row.className="grid g3 outlet-row";row.innerHTML=`<label>Diameter (in)<input class="o_d" value="2.5" inputmode="decimal"></label><label>C (coeff)<input class="o_c" value="0.9" inputmode="decimal"></label><label># Outlets<input class="o_n" value="1" inputmode="numeric" pattern="\d*"></label>`;el("#outlets").appendChild(row)});
  el("#record").addEventListener("click",()=>{if(!ensureRequiredFilled("f")){toast("Fill required fields first.","warn");return}const res=calcFlow();state.data.details.push({hydID:+el("#f_hydrant").value.trim(),EntryDate:el("#f_date").value.trim(),Static:parseFloat(el("#f_static").value||"")||"",Residual:parseFloat(el("#f_residual").value||"")||"",Pilot:parseFloat(el("#f_pitot").value||"")||"", "Total Discharge":Math.round(res.totalQ||0),"Available Fire Flow":Math.round(res.aff||0),Notes:el("#f_notes").value.trim()});store.set("rc_data",state.data);toast("Flow entry recorded.");renderDashboard();renderHydrants()});
  el("#miRecord").addEventListener("click",()=>{if(!ensureRequiredFilled("m")){toast("Fill required fields first.","warn");return}const hyd=+el("#m_hydrant").value.trim(),date=el("#m_date").value.trim(),status=el("#m_status").value,notes=el("#m_notes").value.trim();const h=state.data.hydrants.find(x=>+x.HydID===hyd);if(h){h.Status=status}state.data.details.push({hydID:hyd,EntryDate:date,Notes:`M&I: ${status}${notes?(" – "+notes):""}`});store.set("rc_data",state.data);toast("M&I saved.");renderDashboard();renderHydrants()});
  function lockPrompt(kind,count){return new Promise(res=>{const ans=confirm(`Imported ${count} ${kind} rows.\n\nLock these rows from editing going forward?`);res(ans)})}
  el("#imp_master").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;const text=await f.text();const rows=parseCSV(text);const hdr=rows.shift().map(h=>h.trim());const cols={TestNeeded:hdr.indexOf("TestNeeded"),HydID:hdr.indexOf("HydID"),Name:hdr.indexOf("Name"),Lat:hdr.indexOf("Lat (DD)"),Lon:hdr.indexOf("Lon (DD)"),District:hdr.indexOf("District"),Location:hdr.indexOf("Location"),Make:hdr.indexOf("Make"),LineSize:hdr.indexOf("LineSize"),Top:hdr.indexOf("Top"),Caps:hdr.indexOf("Caps"),Notes:hdr.indexOf("Notes")};const imp=[];rows.forEach(r=>{if(!r[cols.HydID])return;imp.push({TestNeeded:(r[cols.TestNeeded]]||"").toLowerCase()==="true",HydID:+r[cols.HydID]||null,Name:r[cols.Name]||"",Lat:parseFloat(r[cols.Lat]||"")||null,Lon:parseFloat(r[cols.Lon]||"")||null,District:r[cols.District]||"",Location:r[cols.Location]||"",Make:r[cols.Make]||"",LineSize:r[cols.LineSize]||"",Top:r[cols.Top]||"",Caps:r[cols.Caps]||"",Notes:r[cols.Notes]||"",Status:"OK"})});const byId=Object.fromEntries(state.data.hydrants.map(h=>[+h.HydID,h]));imp.forEach(h=>{byId[h.HydID]={...(byId[h.HydID]||{}),...h}});state.data.hydrants=Object.values(byId).sort((a,b)=>(+a.HydID)-(+b.HydID));if(imp.length){const lock=await lockPrompt("master",imp.length);if(lock){state.data.locks.masters.push(new Date().toISOString());toast("Master rows locked.","ok")}}store.set("rc_data",state.data);toast(`Imported ${imp.length} master rows.`);renderDashboard();renderHydrants();e.target.value=""});
  el("#imp_detail").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;const text=await f.text();const rows=parseCSV(text);const hdr=rows.shift().map(h=>h.trim());const col={hydID:hdr.findIndex(h=>h.toLowerCase()==="hydid"||h==="hydID"),Pilot:hdr.indexOf("Pilot"),Static:hdr.indexOf("Static"),MainOutlet:hdr.indexOf("MainOutlet"),TtlDsch:hdr.indexOf("TtlDsch"),Residual:hdr.indexOf("Residual"),EntryDate:hdr.indexOf("EntryDate"),Notes:hdr.indexOf("Notes"),TD:hdr.indexOf("Total Discharge"),AFF:hdr.indexOf("Available Fire Flow")};const imp=[];rows.forEach(r=>{const hyd=r[col.hydID];if(!hyd)return;imp.push({hydID:+hyd,Pilot:r[col.Pilot]||"",Static:r[col.Static]||"",MainOutlet:r[col.MainOutlet]||"",TtlDsch:r[col.TtlDsch]||"",Residual:r[col.Residual]||"",EntryDate:r[col.EntryDate]||"",Notes:r[col.Notes]||"", "Total Discharge":r[col.TD]||"", "Available Fire Flow":r[col.AFF]||""})});state.data.details.push(...imp);if(imp.length){const lock=await lockPrompt("detail",imp.length);if(lock){state.data.locks.details.push(new Date().toISOString());toast("Detail rows locked.","ok")}}store.set("rc_data",state.data);toast(`Imported ${imp.length} detail rows.`);e.target.value=""});
  el("#export_json").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(state.data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="redcap_data.json";a.click()});
  el("#export_csv").addEventListener("click",()=>{const hdr=["hydID","EntryDate","Static","Residual","Pilot","Total Discharge","Available Fire Flow","Notes"];const rows=[hdr.join(",")].concat(state.data.details.map(d=>hdr.map(h=>String(d[h]??"").replace(/"/g,'""')).map(s=>`"${s}"`).join(",")));const blob=new Blob([rows.join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="redcap_details.csv";a.click()});
  function fillStatusSelect(){const sel=document.querySelector("#m_status");sel.innerHTML="";meta.statuses.forEach(s=>{const opt=document.createElement("option");opt.value=s.name;opt.textContent=s.name;sel.appendChild(opt)})}
  function renderMiLists(){const c=document.querySelector("#m_checklist"),t=document.querySelector("#m_tasks");c.innerHTML="";t.innerHTML="";meta.checklist.forEach(txt=>{const row=document.createElement("label");row.className="toolbar";row.innerHTML=`<input type="checkbox"><span>${txt}</span>`;c.appendChild(row)});meta.tasks.forEach(txt=>{const row=document.createElement("label");row.className="toolbar";row.innerHTML=`<input type="checkbox"><span>${txt}</span>`;t.appendChild(row)})}
  renderDashboard();renderHydrants();renderSettingsEditors();renderMiLists();
})();